services:
  mangayomi_client:
    image: username/mangayomi-client:v0.0.0
    environment:
      - API_URL=https://your-api-url.com
    networks:
      - externa
      - interna
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=false"
        - "traefik.http.services.mangayomi_client.loadbalancer.server.port=3000"
        - "traefik.http.services.mangayomi_client.loadbalancer.passHostHeader=true"
        - "traefik.http.routers.mangayomi_client.service=mangayomi_client"
        - "traefik.http.routers.mangayomi_client.rule=Host(`app.mangayomi.com.br`)"
        - "traefik.http.routers.mangayomi_client.tls.certresolver=le"
        - "traefik.http.routers.mangayomi_client.entrypoints=websecure"
        - "traefik.http.routers.mangayomi_client.tls=true"

networks:
  externa:
    external: true
  interna:
    external: true
